version: '3.8'

services:

  api:
    build:
      context: ./api
      target: dev
    ports:
      - 5000:5000
    volumes:
      - $PWD/api/src:/app/src

  client:
    build:
      context: ./client
      target: dev
    ports:
      - 8080:8080
    volumes:
      - $PWD/client/src:/app/src
      - /app/node_modules